import { useState, useEffect, useRef } from "react";
import "./PrintView.css";

function PrintView({ gridRef, userProfile, calculatedData }) {
  const [showPrintView, setShowPrintView] = useState(false);
  const printContentRef = useRef(null);

  const handlePrint = () => {
    window.print();
  };

  // Clone the grid content for print preview
  useEffect(() => {
    if (showPrintView && gridRef.current && printContentRef.current) {
      const originalGrid = gridRef.current;
      const printGrid = printContentRef.current;

      // Clone the grid
      const clonedGrid = originalGrid.cloneNode(true);

      // Copy computed styles
      const originalStyles = window.getComputedStyle(originalGrid);
      clonedGrid.style.cssText = Array.from(originalStyles).reduce(
        (str, key) => `${str}${key}:${originalStyles.getPropertyValue(key)};`,
        "",
      );

      // Clear and append
      printGrid.innerHTML = "";
      printGrid.appendChild(clonedGrid);
    }
  }, [showPrintView, gridRef]);

  return (
    <>
      <div className="print-view-toggle">
        <button
          className="print-btn"
          onClick={() => setShowPrintView(!showPrintView)}
        >
          🖨️ {showPrintView ? "Hide Print View" : "Print View"}
        </button>
      </div>

      {showPrintView && (
        <div className="print-view-container">
          <div className="print-header">
            <h1>My Life in Weeks</h1>
            {userProfile && (
              <p className="print-subtitle">
                Born: {userProfile.birthdate} | Life Expectancy:{" "}
                {userProfile.lifeExpectancy} years
              </p>
            )}
            {calculatedData && (
              <p className="print-stats">
                Age: {calculatedData.age} | Weeks Lived:{" "}
                {calculatedData.weeksLived.toLocaleString()} | Weeks Remaining:{" "}
                {calculatedData.weeksRemaining.toLocaleString()}
              </p>
            )}
            <p className="print-date">
              Printed on: {new Date().toLocaleDateString()}
            </p>
          </div>

          <div className="print-grid" ref={printContentRef}>
            {/* The grid will be cloned here for printing */}
          </div>

          <div className="print-footer">
            <p>Generated by Life in Weeks</p>
          </div>

          <div className="print-actions">
            <button className="print-btn-primary" onClick={handlePrint}>
              🖨️ Print Now
            </button>
          </div>
        </div>
      )}
    </>
  );
}

export default PrintView;
